// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package handler is a generated GoMock package.
package handler

import (
	context "context"
	reflect "reflect"
	model "stori-challenge/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// ProcessCsv mocks base method.
func (m *Mockservice) ProcessCsv(arg0 context.Context) (*model.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessCsv", arg0)
	ret0, _ := ret[0].(*model.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessCsv indicates an expected call of ProcessCsv.
func (mr *MockserviceMockRecorder) ProcessCsv(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCsv", reflect.TypeOf((*Mockservice)(nil).ProcessCsv), arg0)
}
